{
    'name': 'Obras Pro',
    'version': '18.0.1.0.0',
    'summary': 'Módulo para gerenciar projetos de construção, incluindo etapas, lotes e documentos.',
    'category': 'Project',
    'author': 'Datasheep, Joao Henrique',
    'depends': ['base', 'portal', 'website'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/work_stage.xml',
        'data/work_actions.xml',
        'data/demo_work_types.xml',
        'views/work_management_kanban_views.xml',
        'views/work_stage_views.xml',
        'views/work_property_views.xml',
        'views/work_type_views.xml',
        'views/work_document_type_views.xml',
        'views/work_document_views.xml',
        'views/portal_menu.xml',
        'views/portal_templates.xml',
        'data/menu_views.xml',
    ],
    'application': True,
}